package uk.co.aw125.training.models;

import java.util.LinkedList;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import org.jongo.marshall.jackson.oid.MongoObjectId;

import io.swagger.annotations.ApiModelProperty;

@XmlRootElement(name = "Excercise")
public class Excercise {

	@ApiModelProperty(hidden = true, notes = "generated by mongodb")

	@MongoObjectId
	private String id;
	String name;

	List<Tag> tags;
	
	
	public Excercise() {
		tags = new LinkedList<Tag>();
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@XmlElement(name = "name")
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	public List<Tag> getTags() {
		return tags;
	}

	public void setTags(List<Tag> tags) {
		this.tags = tags;
	}


}
