package uk.co.aw125.training.models;

import javax.xml.bind.annotation.XmlRootElement;

import org.jongo.marshall.jackson.oid.MongoId;
import org.jongo.marshall.jackson.oid.MongoObjectId;

import io.swagger.annotations.ApiModelProperty;

@XmlRootElement(name = "User")
public class Set {

	@ApiModelProperty(hidden = true, notes = "generated by mongodb")
	@MongoId
	@MongoObjectId
	private String id;
	private String username;
	private int bodyWeight;
	private int weight;
	private int targetReps;
	private int actualReps;
	private Mood mood;
	private Excercise excercise;
	

	public Set() {
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public int getBodyWeight() {
		return bodyWeight;
	}

	public void setBodyWeight(int bodyWeight) {
		this.bodyWeight = bodyWeight;
	}

	public int getWeight() {
		return weight;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

	public int getTargetReps() {
		return targetReps;
	}

	public void setTargetReps(int targetReps) {
		this.targetReps = targetReps;
	}

	public int getActualReps() {
		return actualReps;
	}

	public void setActualReps(int actualReps) {
		this.actualReps = actualReps;
	}

	public Mood getMood() {
		return mood;
	}

	public void setMood(Mood mood) {
		this.mood = mood;
	}

	public Excercise getExcercise() {
		return excercise;
	}

	public void setExcercise(Excercise excercise) {
		this.excercise = excercise;
	}
	
	


}