package uk.co.aw125.training.models.core;

import javax.xml.bind.annotation.XmlTransient;

import org.jongo.marshall.jackson.oid.MongoObjectId;

import io.swagger.annotations.ApiModelProperty;


public class Mood {

  @XmlTransient
  @ApiModelProperty(hidden = true, notes = "generated by mongodb")
  @MongoObjectId
  private String _id;
  String name;

  public Mood() {}



  public String get_id() {
    return _id;
  }



  public void set_id(String _id) {
    this._id = _id;
  }



  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

}
