package uk.co.aw125.training.models.core;

import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlTransient;

import org.jongo.marshall.jackson.oid.MongoObjectId;

import io.swagger.annotations.ApiModelProperty;


public class Session {

  @XmlTransient
  @ApiModelProperty(hidden = true, notes = "generated by mongodb")
  @MongoObjectId
  private String _id;
  @XmlTransient
  @ApiModelProperty(hidden = true, notes = "generated by mongodb")
  private String username;
  @NotNull
  private Double bodyWeight;
  @NotNull
  private int restingHeartRate;
  @NotNull
  private String mood;

  private boolean injured = false;

  private boolean creatine = false;

  private boolean competition = false;
  
  private Double volume;
  
  private int intensity;
  
  private int sets;

  // @XmlTransient
  // @ApiModelProperty(hidden = true, notes = "generated by mongodb")
  private Date date;


  public String get_id() {
    return _id;
  }


  public void set_id(String _id) {
    this._id = _id;
  }


  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }



  public String getMood() {
    return mood;
  }



  public void setMood(String mood) {
    this.mood = mood;
  }


  public Double getBodyWeight() {
    return bodyWeight;
  }


  public void setBodyWeight(Double bodyWeight) {
    this.bodyWeight = bodyWeight;
  }


  public int getRestingHeartRate() {
    return restingHeartRate;
  }


  public void setRestingHeartRate(int restingHeartRate) {
    this.restingHeartRate = restingHeartRate;
  }


  public boolean isInjured() {
    return injured;
  }


  public void setInjured(boolean injured) {
    this.injured = injured;
  }


  public boolean isCreatine() {
    return creatine;
  }


  public void setCreatine(boolean creatine) {
    this.creatine = creatine;
  }


  public boolean isCompetition() {
    return competition;
  }


  public void setCompetition(boolean competition) {
    this.competition = competition;
  }


  public Double getVolume() {
    return volume;
  }


  public void setVolume(Double volume) {
    this.volume = volume;
  }


  public int getIntensity() {
    return intensity;
  }


  public void setIntensity(int intensity) {
    this.intensity = intensity;
  }


  public int getSets() {
    return sets;
  }


  public void setSets(int sets) {
    this.sets = sets;
  }


  public Date getDate() {
    return date;
  }


  public void setDate(Date date) {
    this.date = date;
  }

  
  public void addSet()
  {
    this.sets++;
  }
  
  public void addVolume(Double weight, int reps)
  {
    if (this.volume == null)
    {
      this.volume = Double.valueOf(0);
    }
    this.volume = this.volume + (weight * reps);
  }
  

}
