package uk.co.aw125.training.models.core;

import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlTransient;

import org.jongo.marshall.jackson.oid.MongoObjectId;

import io.swagger.annotations.ApiModelProperty;


public class Set {

  @XmlTransient
  @ApiModelProperty(hidden = true, notes = "generated by mongodb")
  @MongoObjectId
  private String _id;
  @XmlTransient
  @ApiModelProperty(hidden = true, notes = "generated by mongodb")
  private String username;
  @NotNull
  private Double bodyWeight;
  @NotNull
  private Double weight;
  @NotNull
  private int targetReps;
  @NotNull
  private int restingHeartRate;
  @NotNull
  private String mood;

  @NotNull
  private int actualReps;
  
  @ApiModelProperty(hidden = true, notes = "calculated")
  private Double predictedMax;
  
  @NotNull
  private Double trainingMax;


  private boolean injured = false;

  private boolean creatine = false;

  private boolean competition = false;

  @NotNull
  private String excercise;

  // @XmlTransient
  // @ApiModelProperty(hidden = true, notes = "generated by mongodb")
  private Date date;


  public String get_id() {
    return _id;
  }

  public void set_id(String _id) {
    this._id = _id;
  }

  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }


  public int getTargetReps() {
    return targetReps;
  }

  public void setTargetReps(int targetReps) {
    this.targetReps = targetReps;
  }

  public int getActualReps() {
    return actualReps;
  }

  public void setActualReps(int actualReps) {
    this.actualReps = actualReps;
  }



  public String getMood() {
    return mood;
  }



  public void setMood(String mood) {
    this.mood = mood;
  }



  public String getExcercise() {
    return excercise;
  }



  public void setExcercise(String excercise) {
    this.excercise = excercise;
  }



  public Date getDate() {
    return date;
  }



  public void setDate(Date date) {
    this.date = date;
  }



  public boolean isInjured() {
    return injured;
  }



  public void setInjured(boolean injured) {
    this.injured = injured;
  }



  public boolean isCreatine() {
    return creatine;
  }



  public void setCreatine(boolean creatine) {
    this.creatine = creatine;
  }



  public int getRestingHeartRate() {
    return restingHeartRate;
  }



  public void setRestingHeartRate(int restingHeartRate) {
    this.restingHeartRate = restingHeartRate;
  }



  public boolean isCompetition() {
    return competition;
  }



  public void setCompetition(boolean competition) {
    this.competition = competition;
  }



  public Double getBodyWeight() {
    return bodyWeight;
  }



  public void setBodyWeight(Double bodyWeight) {
    this.bodyWeight = bodyWeight;
  }



  public Double getWeight() {
    return weight;
  }



  public void setWeight(Double weight) {
    this.weight = weight;
  }

  public Double getPredictedMax() {
    return predictedMax;
  }

  public void setPredictedMax(Double predictedMax) {
    this.predictedMax = predictedMax;
  }

  public Double getTrainingMax() {
    return trainingMax;
  }

  public void setTrainingMax(Double trainingMax) {
    this.trainingMax = trainingMax;
  }


  public void updatePredictedMax()
  {
    this.predictedMax = this.weight * (1 + this.actualReps * 0.033);
  }
  

}
