package uk.co.aw125.training.models.core;

import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlTransient;

import org.jongo.marshall.jackson.oid.MongoObjectId;

import io.swagger.annotations.ApiModelProperty;


public class Set {

  @XmlTransient
  @ApiModelProperty(hidden = true, notes = "generated by mongodb")
  @MongoObjectId
  private String _id;
  @NotNull
  private String username;
  @NotNull
  private int bodyWeight;
  @NotNull
  private int weight;
  @NotNull
  private int targetReps;
  @NotNull
  private int actualReps;
  @NotNull
  private String mood;
  @NotNull
  private String excercise;


  public Set() {}



  public String get_id() {
    return _id;
  }



  public void set_id(String _id) {
    this._id = _id;
  }



  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public int getBodyWeight() {
    return bodyWeight;
  }

  public void setBodyWeight(int bodyWeight) {
    this.bodyWeight = bodyWeight;
  }

  public int getWeight() {
    return weight;
  }

  public void setWeight(int weight) {
    this.weight = weight;
  }

  public int getTargetReps() {
    return targetReps;
  }

  public void setTargetReps(int targetReps) {
    this.targetReps = targetReps;
  }

  public int getActualReps() {
    return actualReps;
  }

  public void setActualReps(int actualReps) {
    this.actualReps = actualReps;
  }



  public String getMood() {
    return mood;
  }



  public void setMood(String mood) {
    this.mood = mood;
  }



  public String getExcercise() {
    return excercise;
  }



  public void setExcercise(String excercise) {
    this.excercise = excercise;
  }



}
