package uk.co.aw125.training.models.core;

import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlTransient;

import org.jongo.marshall.jackson.oid.MongoObjectId;

import io.swagger.annotations.ApiModelProperty;


public class Sets {

  @XmlTransient
  @ApiModelProperty(hidden = true, notes = "generated by mongodb")
  @MongoObjectId
  private String _id;
  @XmlTransient
  @ApiModelProperty(hidden = true, notes = "generated by mongodb")
  private String username;
  @NotNull
  private Double bodyWeight;
  @NotNull
  private int restingHeartRate;
  @NotNull
  private String mood;
  
  @NotNull
  private String excercise;

  private boolean injured = false;

  private boolean creatine = false;

  private boolean competition = false;

  private Double trainingLoad;

  private Double predictedMax;

  private Double trainingMax;

  private int volume;

  private int intensity;

  private int sets;

  // @XmlTransient
  // @ApiModelProperty(hidden = true, notes = "generated by mongodb")
  private Date date;


  public String get_id() {
    return _id;
  }


  public void set_id(String _id) {
    this._id = _id;
  }


  public String getUsername() {
    return username;
  }

  public void setUsername(String username) {
    this.username = username;
  }



  public String getMood() {
    return mood;
  }



  public void setMood(String mood) {
    this.mood = mood;
  }


  public Double getBodyWeight() {
    return bodyWeight;
  }


  public void setBodyWeight(Double bodyWeight) {
    this.bodyWeight = bodyWeight;
  }


  public int getRestingHeartRate() {
    return restingHeartRate;
  }


  public void setRestingHeartRate(int restingHeartRate) {
    this.restingHeartRate = restingHeartRate;
  }


  public boolean isInjured() {
    return injured;
  }


  public void setInjured(boolean injured) {
    this.injured = injured;
  }


  public boolean isCreatine() {
    return creatine;
  }


  public void setCreatine(boolean creatine) {
    this.creatine = creatine;
  }


  public boolean isCompetition() {
    return competition;
  }


  public void setCompetition(boolean competition) {
    this.competition = competition;
  }


  public int getIntensity() {
    return intensity;
  }


  public void setIntensity(int intensity) {
    this.intensity = intensity;
  }


  public int getSets() {
    return sets;
  }


  public void setSets(int sets) {
    this.sets = sets;
  }


  public Date getDate() {
    return date;
  }


  public void setDate(Date date) {
    this.date = date;
  }


  public void addSet() {
    this.sets++;
  }


  public Double getTrainingLoad() {
    return trainingLoad;
  }


  public void setTrainingLoad(Double trainingLoad) {
    this.trainingLoad = trainingLoad;
  }


  public Double getPredictedMax() {
    return predictedMax;
  }


  public void setPredictedMax(Double predictedMax) {
    this.predictedMax = predictedMax;
  }


  public Double getTrainingMax() {
    return trainingMax;
  }


  public void setTrainingMax(Double trainingMax) {
    this.trainingMax = trainingMax;
  }


  public int getVolume() {
    return volume;
  }


  public void setVolume(int volume) {
    this.volume = volume;
  }


  public void addVolume(int reps) {
    this.volume += reps;
  }

  
  public String getExcercise() {
    return excercise;
  }


  public void setExcercise(String excercise) {
    this.excercise = excercise;
  }


  public void addTrainingLoad(Double weight, int reps) {
    if (this.trainingLoad == null) {
      this.trainingLoad = Double.valueOf(0);
    }
    this.trainingLoad = this.trainingLoad + (weight * reps);
  }

  public void updatePredictedMax(Double predictedMax) {
    if (this.predictedMax == null) {
      this.predictedMax = predictedMax;

    } else if (predictedMax > this.predictedMax) {
      this.predictedMax = predictedMax;
    }
  }


}
