---

- name: install jdk
  yum: name="{{item}}" state=present
  with_items:
     - "jdk"
  become_user: root
  become: True
  
- name: install tomcat
  yum: name="{{item}}" state=present
  with_items:
     - "tomcat"
  become_user: root
  become: True